# Generated by Django 3.2.9 on 2021-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
