# Generated by Django 3.2.9 on 2021-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211126_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
